# GitHub Labels Configuration
# This file defines all labels used in the repository
# Labels are automatically synced by the label-sync workflow

- name: "github-actions"
  color: "000000"
  description: "Pull requests that update GitHub Actions code"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "python"
  color: "3572A5"
  description: "Pull requests that update Python code"

- name: "docker"
  color: "2496ED"
  description: "Pull requests that update Docker code"

- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "security"
  color: "d93f0b"
  description: "Security-related issues"

- name: "maintenance"
  color: "fbca04"
  description: "Maintenance and chores"
